"""
    Lagrello API

    API specification for Lagrello, a simple to use authentication service  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lagrello.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import lagrello_client
from lagrello_client.api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_create(self):
        """Test case for users_create

        Creates a user in tenant, tenant is determined from the token  # noqa: E501
        """
        pass

    def test_users_delete(self):
        """Test case for users_delete

        Deletes specified user  # noqa: E501
        """
        pass

    def test_users_get(self):
        """Test case for users_get

        Returns specified user  # noqa: E501
        """
        pass

    def test_users_update(self):
        """Test case for users_update

        Updates specified user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
