"""
    Lagrello API

    API specification for Lagrello, a simple to use authentication service  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lagrello.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import lagrello_client
from lagrello_client.api.images_api import ImagesApi  # noqa: E501


class TestImagesApi(unittest.TestCase):
    """ImagesApi unit test stubs"""

    def setUp(self):
        self.api = ImagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_images_totp(self):
        """Test case for images_totp

        Returns a generated QR code  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
