"""
    Lagrello API

    API specification for Lagrello, a simple to use authentication service  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lagrello.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import lagrello_client
from lagrello_client.api.auth_api import AuthApi  # noqa: E501


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_email_auth(self):
        """Test case for users_email_auth

        Gives back user data for the magic link token  # noqa: E501
        """
        pass

    def test_users_email_send(self):
        """Test case for users_email_send

        This endpoint will be used when you want to send a magic login link to specified user  # noqa: E501
        """
        pass

    def test_users_totp_auth(self):
        """Test case for users_totp_auth

        Verify users TOTP token  # noqa: E501
        """
        pass

    def test_users_totp_toggle(self):
        """Test case for users_totp_toggle

        Enables or disables Time-based One-Time Password authentication method for specified user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
