"""
    Lagrello API

    API specification for Lagrello, a simple to use authentication service  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lagrello.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lagrello_client
from lagrello_client.model.paging import Paging
from lagrello_client.model.token import Token
globals()['Paging'] = Paging
globals()['Token'] = Token
from lagrello_client.model.token_list import TokenList


class TestTokenList(unittest.TestCase):
    """TokenList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenList(self):
        """Test TokenList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TokenList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
