"""
    Lagrello API

    API specification for Lagrello, a simple to use authentication service  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lagrello.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import lagrello_client
from lagrello_client.api.internal_api import InternalApi  # noqa: E501


class TestInternalApi(unittest.TestCase):
    """InternalApi unit test stubs"""

    def setUp(self):
        self.api = InternalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tenants_cardtoken(self):
        """Test case for tenants_cardtoken

        Returns token that is used by stripe to save card number.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
