# flake8: noqa

"""
    Lagrello API

    API specification for Lagrello, a simple to use authentication service  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lagrello.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from lagrello_client.api_client import ApiClient

# import Configuration
from lagrello_client.configuration import Configuration

# import exceptions
from lagrello_client.exceptions import OpenApiException
from lagrello_client.exceptions import ApiAttributeError
from lagrello_client.exceptions import ApiTypeError
from lagrello_client.exceptions import ApiValueError
from lagrello_client.exceptions import ApiKeyError
from lagrello_client.exceptions import ApiException
